[services]
kerberos = true
clouderaHms = true
kafkaKerberos = true

[kerberos]
startupTimeoutSeconds = 180
materialTimeoutSeconds = 120
adminAttempts = 120
adminRetryDelaySeconds = 1
debug = true

[ports]
kafka = 19092

[kafkaTls]
enabled = true
domain = "localhost"

[hiveMetastoreTls]
enabled = true
domain = "localhost"
